_BASE_: "../BaseRetina.yaml"
OUTPUT_DIR: "work_dirs/coco_retinanet"
MODEL:
  META_ARCHITECTURE: "RetinaNet_D2"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50

  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3)] for x in [32, 64, 128, 256, 512]]"]
  
  RETINANET:
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]   
  
  CUSTOM:
    CLS_WEIGHTS: [1., 1., 1., 1., 1.]
    REG_WEIGHTS: [1., 1., 1., 1., 1.]
    FOCAL_LOSS_ALPHAS: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
    FOCAL_LOSS_GAMMAS: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
    
SOLVER:
  # 3x
  # STEPS: (210000, 250000)
  # MAX_ITER: 270000

  # 1x
  STEPS: (30000, 40000)
  MAX_ITER: 50000
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  AMP:
    ENABLED: True
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: value
    CLIP_VALUE: 35.0
    NORM_TYPE: 2.0

TEST:  
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 200

VIS_PERIOD: 0